learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines URLs specific to the learning logs app"""

from django.urls import path

from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home Page
    path('', views.index, name="index"),
    # Topics Page
    path('topics/', views.topics, name="topics"),
    # Individual Topic Page
    path('topics/<int:topic_id>/', views.topic, name="topic"),
    # New Topic Page
    path('new_topic/', views.new_topic, name="new_topic"),
    # New Entry Page
    path('topics/<int:topic_id>/new_entry/', views.new_entry, name="new_entry")
]

learning_logs/models.py
from django.db import models


class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model"""
        return self.text


class Entry(models.Model):
    """An entry within a topic"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        if len(self.text[:50]) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

learning_logs/forms.py
from django import forms

from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ["text"]
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ["text"]
        labels = {'text': 'Entry'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect

from .models import Topic
from .forms import TopicForm, EntryForm

# Create your views here.


def index(request):
    """Return the homepage for Learning Logs"""
    return render(request, 'learning_logs/index.html')


def topics(request):
    """Return the topics page for Learning Logs"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


def topic(request, topic_id):
    """Return a specific Topic"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {
        'topic': topic,
        'entries': entries
    }
    return render(request, 'learning_logs/topic.html', context)


def new_topic(request):
    """Create a new topic"""
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = TopicForm()
    else:
        # POST data submitted; process data
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


def new_entry(request, topic_id):
    """Create a new entry for selected topic"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # No data submitted, create a blank form
        form = EntryForm()
    else:
        # POST data submitted, process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Display a blank or invalid form
    context = {
        'topic': topic,
        'form': form
    }
    return render(request, 'learning_logs/new_entry.html', context)

learning_logs/templates/learning_logs/base.html
<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> |
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %} {% endblock content%}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}

<p>Keeping a log helps you keep track of your learning progress. Learning
    log allows you to log progress on any number of things you are learning</p>

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>

    <p>Add a new entry</p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Add a new topic:</p>

    <form action="{% url 'learning_logs:new_topic' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add Topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<h1>Topic: {{ topic }}</h1>

<p>Entries:</p>

<p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add an entry</a>
</p>

<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no entries for this topic. Try adding one!</li>
    {% endfor %}
</ul>

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<h1>Topics</h1>

<ul>
    {% for topic in topics %}
        <li>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
        </li>
    {% empty %}
        <li>No topics have been added yet. Try adding one!</li>
    {% endfor %}
</ul>

<a href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}